<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Weixuan Dong, Danny Lee, Bruce Zhou">

<title>BST 260 Final Project - COVID-19 Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="final-project_files/libs/clipboard/clipboard.min.js"></script>
<script src="final-project_files/libs/quarto-html/quarto.js"></script>
<script src="final-project_files/libs/quarto-html/popper.min.js"></script>
<script src="final-project_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="final-project_files/libs/quarto-html/anchor.min.js"></script>
<link href="final-project_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="final-project_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="final-project_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="final-project_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="final-project_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#analyses" id="toc-analyses" class="nav-link" data-scroll-target="#analyses">Analyses</a>
  <ul class="collapse">
  <li><a href="#q1-pandemic-period-from-jan-2020-to-nov-2024" id="toc-q1-pandemic-period-from-jan-2020-to-nov-2024" class="nav-link" data-scroll-target="#q1-pandemic-period-from-jan-2020-to-nov-2024">Q1: Pandemic period from Jan 2020 to Nov 2024</a></li>
  <li><a href="#q2-deaths-rate-by-state-during-each-time-period" id="toc-q2-deaths-rate-by-state-during-each-time-period" class="nav-link" data-scroll-target="#q2-deaths-rate-by-state-during-each-time-period">Q2: Deaths rate by state during each time period</a></li>
  <li><a href="#q3-covid-19-became-less-or-more-virulent-across-different-periods" id="toc-q3-covid-19-became-less-or-more-virulent-across-different-periods" class="nav-link" data-scroll-target="#q3-covid-19-became-less-or-more-virulent-across-different-periods">Q3: COVID-19 became less or more virulent across different periods</a>
  <ul class="collapse">
  <li><a href="#cases-fatality-rate-hospitalization-rate-and-death-per-population" id="toc-cases-fatality-rate-hospitalization-rate-and-death-per-population" class="nav-link" data-scroll-target="#cases-fatality-rate-hospitalization-rate-and-death-per-population">Cases fatality rate, hospitalization rate, and death per population</a></li>
  </ul></li>
  <li><a href="#q4-estimate-excess-mortality-for-each-week-for-each-state.-check-if-excess-mortality-can-be-explained-by-covid-19" id="toc-q4-estimate-excess-mortality-for-each-week-for-each-state.-check-if-excess-mortality-can-be-explained-by-covid-19" class="nav-link" data-scroll-target="#q4-estimate-excess-mortality-for-each-week-for-each-state.-check-if-excess-mortality-can-be-explained-by-covid-19">Q4: Estimate excess mortality for each week for each state. Check if excess mortality can be explained by COVID-19</a></li>
  <li><a href="#q5.-for-each-period-compute-the-excess-mortality-rates-by-state.-describe-which-states-did-better-or-worse-during-the-different-periods." id="toc-q5.-for-each-period-compute-the-excess-mortality-rates-by-state.-describe-which-states-did-better-or-worse-during-the-different-periods." class="nav-link" data-scroll-target="#q5.-for-each-period-compute-the-excess-mortality-rates-by-state.-describe-which-states-did-better-or-worse-during-the-different-periods.">Q5. For each period compute the excess mortality rates by state. Describe which states did better or worse during the different periods.</a></li>
  </ul></li>
  <li><a href="#supplementary-methods" id="toc-supplementary-methods" class="nav-link" data-scroll-target="#supplementary-methods">Supplementary Methods</a>
  <ul class="collapse">
  <li><a href="#death-rate-of-each-state-3-waves" id="toc-death-rate-of-each-state-3-waves" class="nav-link" data-scroll-target="#death-rate-of-each-state-3-waves">Death rate of each state (3 waves)</a></li>
  <li><a href="#pair-wise-comparison-of-the-cfr-hr-and-dp-using-statistical-tests" id="toc-pair-wise-comparison-of-the-cfr-hr-and-dp-using-statistical-tests" class="nav-link" data-scroll-target="#pair-wise-comparison-of-the-cfr-hr-and-dp-using-statistical-tests">Pair-wise comparison of the CFR, HR, and DP using statistical tests</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">BST 260 Final Project - COVID-19 Data</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Weixuan Dong, Danny Lee, Bruce Zhou </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>The COVID-19 pandemic, first reported in Wuhan in late 2019, is a respiratory disease caused by the severe acute respiratory syndrome coronavirus 2 (SARS-Cov-2) <span class="citation" data-cites="shi_2020_an covid2021modeling">(<a href="#ref-shi_2020_an" role="doc-biblioref">Shi et al. 2020</a>; <a href="#ref-covid2021modeling" role="doc-biblioref">Covid and Team 2021</a>)</span>. The SAR-Cov-2 virus rapidly spread from China to the rest of the world in early 2020, and has constituted arguably the most severe global health crisis the 21st century has seen so far. Beyond its direct impact on human health, the outbreak of COVID-19 has exerted indelible influence on societies, economies, and the healthcare systems. In the early phase of the COVID-19 pandemic, it was known to cause irreversible pneumonia, high fever, and dry cough <span class="citation" data-cites="madabhavi2020covid">(<a href="#ref-madabhavi2020covid" role="doc-biblioref">Madabhavi, Sarkar, and Kadakol 2020</a>)</span>. Silvestri et al.&nbsp;(2020) identified four stages of the early variants of the SARS-Cov-2 virus: upper respiratory infection, pneumonia, cytokine storm, and in the worse scenario, death <span class="citation" data-cites="stasi2020treatment">(<a href="#ref-stasi2020treatment" role="doc-biblioref">Stasi et al. 2020</a>)</span>.</p>
<p>The rapid transmission of the COVID-19 virus was possibly due to its unique characteristic: asymptomatic transmission. Compared with coronaviruses identified previously such as the MERS-Cov, many of the COVID-19 infected patients did not show any symptoms when they first contracted the virus. However, they already became carriers, and the virus already started spreading from them through air, body fluid exchange, or aerosols <span class="citation" data-cites="gao2021systematic">(<a href="#ref-gao2021systematic" role="doc-biblioref">Gao et al. 2021</a>)</span>. The asymptomatic transmission feature accelerated the wide spread of the COVID-19 virus, and at the same time hindered the containment efforts led by the healthcare agencies. What’s more, as the pandemic progressed and vaccines were developed, the SARS-Cov-2 virus exhibited a high rate of escape and mutation, leading to a variety of variants including alpha, beta, delta, and omicron. These variants showed differences in their transmissibility, virulence, and the ability to evade the immune system. Because of this, even vaccines, which used to be taken as the ultimate measure to end any pandemic, proved to fall short of people’s expectation in controlling this worldwise crisis <span class="citation" data-cites="vasireddy2021review">(<a href="#ref-vasireddy2021review" role="doc-biblioref">Vasireddy et al. 2021</a>)</span>. As a result, the majority of the governments announced emergency measures ranging from mask mandates, social distancing, regular sterilization, and even full lock-down of cities <span class="citation" data-cites="koh2020covid">(<a href="#ref-koh2020covid" role="doc-biblioref">Koh 2020</a>)</span>.</p>
<p>Globally, what the COVID-19 imposed was not merely a challenge in the field of public health, but also a multi-faceted catastrophe. For instance, restrictions on freight transport wreaked great havoc on international transactions and businesses. Consequently, the economic systems of countries around the globe were heavily struck, especially for those which rely greatly on exports. A cascade of its adverse effects was reflected by high rate of unemployment, corporation bankruptcy, disruptions to supply chains, and a switch in working/learning mode. To the healthcare system, COVID-19 meant extraordinary pressure on the infrastructures. Hospitals were often confronted with an overwhelming number of infected patients, while experiencing a lack of medical professionals also due to COVID-19 transmission.</p>
<p>Especially in the United States, the COVID-19 pandemic has been complicated and exacerbated by various factors <span class="citation" data-cites="omer2020covid covid2021modeling">(<a href="#ref-omer2020covid" role="doc-biblioref">Omer, Malani, and Del Rio 2020</a>; <a href="#ref-covid2021modeling" role="doc-biblioref">Covid and Team 2021</a>)</span>. Given the high degree of autonomy of each state in the US, significant variations could be seen across states due to discrepancies in regional public health policies, demographics, and economic development. Previous studies have suggested that the ethnic minorities, middle- and low-income populations, and the rural communities were relatively more vulnerable to this emergency. These populations often suffer from pre-existing health inequities and consequently disproportional rates of mortality were reported <span class="citation" data-cites="alcendor2020racial wilder2021disproportionate">(<a href="#ref-alcendor2020racial" role="doc-biblioref">Alcendor 2020</a>; <a href="#ref-wilder2021disproportionate" role="doc-biblioref">Wilder 2021</a>)</span>.</p>
<p>The US Centers for Disease Control and Prevention (CDC) provides an excellent platform for collecting and sharing COVID-19 related data. These data enable us to study the progression and impact of COVID-19 throughout the pandemic period. We can expect that different states might have responded differently: adopting distinct strategies for containment and mitigation. Additionally, as the COVID-19 virus mutated, multiple waves could be identified, which were driven by seasonal changes, vaccine effectiveness, and the fatality rate. Understanding these patterns is vital to assessing the evolution of the SARS-Cov-2 virus, regional differences, and the virulence over time.</p>
<p>In this project, we examined the COVID-19 data provided by the CDC COVID-19 Response, including COVID-19 cases, COVID-related deaths, and hospitalization from Jan 25th, 2020 to Nov 30th, 2024. Leveraging data analysis and visualization, this study aims to identify major waves of the COVID-19 pandemic in the US, and answer the following questions 1) which states generally responded to the pandemic better, 2) how the virulence of the SARS-Cov-2 virus evolved to understand the regional differences and seasonal changes in the transmissibility of the virus. In addition, we also seek to estimate the weekly excess mortality for each state during the pandemic period, and investigate whether the regional differences could be observed and whether COVID-19 was the driving factor. We hypothesize that states along the west and east coasts would generally have better performance during the pandemic due to stronger healthcare infrastructure. We also hypothesize that the COVID-19 virus became less virulent over time as typically viruses do not possess high virulence and high contagiousness.</p>
</section>
<section id="analyses" class="level1">
<h1>Analyses</h1>
<section id="q1-pandemic-period-from-jan-2020-to-nov-2024" class="level2">
<h2 class="anchored" data-anchor-id="q1-pandemic-period-from-jan-2020-to-nov-2024">Q1: Pandemic period from Jan 2020 to Nov 2024</h2>
<p>The figure below displays the COVID-19 cases, deaths, and hospitalization rate per 100,000 people in each region of the US from 2020 to 2024.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final-project_files/figure-html/trend%20plots-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>As can be seen from the trend plot which depicts the rates of COVID-19 cases, deaths, and hospitalizations from 01/25/2021 to 11/30/2024, there seems to be 3 waves of COVID-19 spread. The first one occurs from Oct 2020 to Apr 2021, where a peak in cases, deaths, and hospitalizations can be observed. Likewise, it appears that there was another wave between Jul 2021 to early Dec 2021. Lastly, there was a wave from early Dec 2021 to Apr 2022.</p>
<p><strong>First Wave</strong></p>
<p>This period marked the first significant rise in COVID-19 rates, with sharp increases across all metrics—cases, deaths, and hospitalizations. The wave coincides with the colder months when indoor gatherings increased and may also reflect the impact of delayed public health measures or variants circulating during this time. The peak of this wave aligns with the early rollout of vaccines, which likely contributed to its decline as more people gained access to immunization.</p>
<p><strong>Second Wave</strong></p>
<p>The summer and early winter of 2021 saw a resurgence in COVID-19 activity, driven largely by the spread of the Delta variant. This wave demonstrates a rapid increase in hospitalizations and deaths following the initial rise in cases. Despite vaccination efforts, breakthrough infections and the highly contagious nature of Delta played significant roles in this period. Public health measures such as mask mandates were reinstituted in some areas, but the surge continued through the fall.</p>
<p><strong>Third Wave</strong></p>
<p>The final and most intense wave depicted occurred during the winter of 2021-2022, fueled by the Omicron variant. While cases skyrocketed to unprecedented levels due to Omicron’s transmissibility, deaths and hospitalizations rose less dramatically than in previous waves, likely reflecting the variant’s comparatively milder effects and increased vaccination coverage. However, the healthcare system faced immense strain due to the sheer number of cases.</p>
</section>
<section id="q2-deaths-rate-by-state-during-each-time-period" class="level2">
<h2 class="anchored" data-anchor-id="q2-deaths-rate-by-state-during-each-time-period">Q2: Deaths rate by state during each time period</h2>
<p>From Oct 1st 2020 to Apr 1st 2021, overall this wave was arguably the most severe wave among all 3. The highest death rate per 100,000 people was reported in South Dakota (SD), with an average of 188.91 deaths among 100,000 people. Following South Dakota were North Dakota (177.97), Oklahoma (175.32), and Arkansas (150.17). There were also states which managed to contain the death rate below 50 per 100,000. For example, the lowest death rate was reported in Hawaii, which was only 9.12 deaths on average per 100,000 people, followed by Vermont (11.18), Alaska (26.48), Washington (39.58), Oregon (42.04), Puerto Rico (43.66), and Maine (47.19).</p>
<p>From July 1st 2021 to Dec 1st 2021, the COVID-19 variant seemed to be less virulent. The highest death rate per 100,000 people was reported in West Virginia (WV), with an average of 113.13 deaths among 100,000 people. Following West Virginia were Florida (111.62), Montana (111.30), and Wyoming (109.88). There were also states which managed to contain the death rate below 40 per 100,000. For example, the lowest death rate was reported in Washington D.C., which was only 12.09 deaths on average per 100,000 people, followed by Vermont (12.39), Connecticut (12.39), New York (17.04), and Hawaii (36.83).</p>
<p>For the third wave, the COVID-19 variant during the period seemed to grow more infectious and deadly. The highest death rate per 100,000 people was reported in West Virginia (WV) again, with an average of 103.73 deaths among 100,000 people. Following West Virginia were Ohio (102.05), New Mexico (96.78), and Kentucky (93.82). There were also states which managed to contain the death rate below 40 per 100,000. For example, the lowest death rate was reported in Hawaii, which was only 20.76 deaths on average per 100,000 people, followed by Alaska (27.69), Puerto Rico (28.21), Vermont (29.85), and Utah (33.22). Figures can be found in <strong>Supplementary Methods</strong>.</p>
<p>We also compared the performance of each state across all 3 waves by taking the average of their death rate per 100,000 people. Results show that Oklahoma had the highest average death rate per 100,000, amounting to 120.00 deaths per 100,000 people, followed by West Virginia (115.33), Mississippi (109), Kentucky (107.42), Tennessee (106.92). There were also states which kept a relatively low death rate across waves. Namely, Vermont had an average death rate of only 17.81 per 100,000. Similarly, Hawaii had an average of 22.24 per 100,000, followed by Puerto Rico (30.94) New York (37.10), and Washington (40.07).</p>
<p>Generally, it can be seen that states in the northeastern part or the west coast of the US performed better than those in the middle or west US. It can also be observed that less populated states such as Vermont and Washington had lower death rates. But exceptions are also evident, for New York is rather populated but it was among the states with the lowest average death rates.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final-project_files/figure-html/avg%20death%20rate%20across%203%20waves-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="q3-covid-19-became-less-or-more-virulent-across-different-periods" class="level2">
<h2 class="anchored" data-anchor-id="q3-covid-19-became-less-or-more-virulent-across-different-periods">Q3: COVID-19 became less or more virulent across different periods</h2>
<p>To evaluate if COVID-19 became less or more virulent across different time periods, we will employ three key metrics: <strong>cases fatality rate (CFR)</strong>, <strong>hospitalization rate (HR)</strong>, and <strong>death per population (DP)</strong>. The CFR is defined as deaths per case, HR is defined as hospitalizations per case, and DP is defined as deaths per population. In the following analyses, we will analyze these key metrics with tables and visualizations.</p>
<section id="cases-fatality-rate-hospitalization-rate-and-death-per-population" class="level3">
<h3 class="anchored" data-anchor-id="cases-fatality-rate-hospitalization-rate-and-death-per-population">Cases fatality rate, hospitalization rate, and death per population</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Wave</th>
<th style="text-align: left;">Total Cases</th>
<th style="text-align: left;">Total Deaths</th>
<th style="text-align: left;">Total Hospitalization</th>
<th style="text-align: left;">Total Population</th>
<th style="text-align: left;">CFR</th>
<th style="text-align: left;">HR</th>
<th style="text-align: left;">DP</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Wave 1</td>
<td style="text-align: left;">22,403,089</td>
<td style="text-align: left;">348,013</td>
<td style="text-align: left;">1,714,882</td>
<td style="text-align: left;">334,955,562</td>
<td style="text-align: left;">1,553.42</td>
<td style="text-align: left;">7,654.67</td>
<td style="text-align: left;">103.90</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wave 2</td>
<td style="text-align: left;">14,304,772</td>
<td style="text-align: left;">194,568</td>
<td style="text-align: left;">1,122,040</td>
<td style="text-align: left;">335,157,329</td>
<td style="text-align: left;">1,360.16</td>
<td style="text-align: left;">7,843.82</td>
<td style="text-align: left;">58.05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wave 3</td>
<td style="text-align: left;">30,709,203</td>
<td style="text-align: left;">194,326</td>
<td style="text-align: left;">1,183,261</td>
<td style="text-align: left;">336,099,114</td>
<td style="text-align: left;">632.79</td>
<td style="text-align: left;">3,853.12</td>
<td style="text-align: left;">57.82</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Wave 1</strong></p>
<p>During Wave 1, the United States experienced a total of 22,403,089 cases, with 348,013 deaths and 1,714,882 hospitalizations. The total population during this period was 334,955,562. Key metrics calculated include:</p>
<ul>
<li>Case Fatality Rate (CFR): 1,553.42 per 100,000 cases.</li>
<li>Hospitalization Rate (HR): 7,654.67 per 100,000 cases.</li>
<li>Death Proportion (DP): 103.90 deaths per 100,000 population.</li>
</ul>
<p><strong>Wave 2</strong></p>
<p>Wave 2 saw a decrease in total cases and deaths compared to Wave 1, with 14,304,772 cases, 194,568 deaths, and 1,122,040 hospitalizations. The total population for this wave was 335,157,329. Metrics for this wave include:</p>
<ul>
<li>Case Fatality Rate (CFR): 1,360.16 per 100,000 cases.</li>
<li>Hospitalization Rate (HR): 7,843.82 per 100,000 cases.</li>
<li>Death Proportion (DP): 58.05 deaths per 100,000 population.</li>
</ul>
<p><strong>Wave 3</strong></p>
<p>Wave 3 reported the highest total cases at 30,709,203, but a similar total death count compared to Wave 2, with 194,326 deaths and 1,183,261 hospitalizations. The total population during this wave was 336,099,114. Metrics calculated for Wave 3 include:</p>
<ul>
<li>Case Fatality Rate (CFR): 632.79 per 100,000 cases.</li>
<li>Hospitalization Rate (HR): 3,853.12 per 100,000 cases.</li>
<li>Death Proportion (DP): 57.82 deaths per 100,000 population.</li>
</ul>
<p>Total cases peaked in Wave 3, while total deaths and hospitalizations decreased relative to Wave 1. The Case Fatality Rate (CFR) showed a marked decline across waves, decreasing from 1,553.42 in Wave 1 to 632.79 in Wave 3. The Hospitalization Rate (HR) also declined significantly by Wave 3, from 7,654.67 in Wave 1 to 3,853.12 in Wave 3. Death Proportion (DP) decreased steadily across the waves, dropping from 103.90 in Wave 1 to 57.82 in Wave 3.</p>
</section>
</section>
<section id="q4-estimate-excess-mortality-for-each-week-for-each-state.-check-if-excess-mortality-can-be-explained-by-covid-19" class="level2">
<h2 class="anchored" data-anchor-id="q4-estimate-excess-mortality-for-each-week-for-each-state.-check-if-excess-mortality-can-be-explained-by-covid-19">Q4: Estimate excess mortality for each week for each state. Check if excess mortality can be explained by COVID-19</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final-project_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Model Results by State</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 16%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">state_name</th>
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">r.squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alabama</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">16.015</td>
<td style="text-align: right;">24.090</td>
<td style="text-align: right;">0.665</td>
<td style="text-align: right;">0.507</td>
<td style="text-align: right;">0.656</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alabama</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.520</td>
<td style="text-align: right;">0.136</td>
<td style="text-align: right;">18.515</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.656</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alaska</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">10.342</td>
<td style="text-align: right;">4.749</td>
<td style="text-align: right;">2.178</td>
<td style="text-align: right;">0.033</td>
<td style="text-align: right;">0.745</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alaska</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.907</td>
<td style="text-align: right;">0.211</td>
<td style="text-align: right;">13.767</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.745</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Arizona</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">66.662</td>
<td style="text-align: right;">32.297</td>
<td style="text-align: right;">2.064</td>
<td style="text-align: right;">0.040</td>
<td style="text-align: right;">0.667</td>
</tr>
<tr class="even">
<td style="text-align: left;">Arizona</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.468</td>
<td style="text-align: right;">0.129</td>
<td style="text-align: right;">19.207</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.667</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Arkansas</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">50.810</td>
<td style="text-align: right;">17.269</td>
<td style="text-align: right;">2.942</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">0.521</td>
</tr>
<tr class="even">
<td style="text-align: left;">Arkansas</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.246</td>
<td style="text-align: right;">0.166</td>
<td style="text-align: right;">13.523</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.521</td>
</tr>
<tr class="odd">
<td style="text-align: left;">California</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">124.611</td>
<td style="text-align: right;">122.045</td>
<td style="text-align: right;">1.021</td>
<td style="text-align: right;">0.309</td>
<td style="text-align: right;">0.683</td>
</tr>
<tr class="even">
<td style="text-align: left;">California</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.453</td>
<td style="text-align: right;">0.123</td>
<td style="text-align: right;">19.878</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.683</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Colorado</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">42.375</td>
<td style="text-align: right;">21.729</td>
<td style="text-align: right;">1.950</td>
<td style="text-align: right;">0.053</td>
<td style="text-align: right;">0.499</td>
</tr>
<tr class="even">
<td style="text-align: left;">Colorado</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.352</td>
<td style="text-align: right;">0.177</td>
<td style="text-align: right;">13.290</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.499</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Connecticut</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-26.603</td>
<td style="text-align: right;">17.044</td>
<td style="text-align: right;">-1.561</td>
<td style="text-align: right;">0.121</td>
<td style="text-align: right;">0.671</td>
</tr>
<tr class="even">
<td style="text-align: left;">Connecticut</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.142</td>
<td style="text-align: right;">0.121</td>
<td style="text-align: right;">17.738</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.671</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Delaware</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">4.135</td>
<td style="text-align: right;">5.807</td>
<td style="text-align: right;">0.712</td>
<td style="text-align: right;">0.478</td>
<td style="text-align: right;">0.682</td>
</tr>
<tr class="even">
<td style="text-align: left;">Delaware</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.434</td>
<td style="text-align: right;">0.164</td>
<td style="text-align: right;">14.867</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.682</td>
</tr>
<tr class="odd">
<td style="text-align: left;">District of Columbia</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">7.151</td>
<td style="text-align: right;">7.928</td>
<td style="text-align: right;">0.902</td>
<td style="text-align: right;">0.370</td>
<td style="text-align: right;">0.475</td>
</tr>
<tr class="even">
<td style="text-align: left;">District of Columbia</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.311</td>
<td style="text-align: right;">0.272</td>
<td style="text-align: right;">8.513</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.475</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Florida</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">66.037</td>
<td style="text-align: right;">84.759</td>
<td style="text-align: right;">0.779</td>
<td style="text-align: right;">0.437</td>
<td style="text-align: right;">0.631</td>
</tr>
<tr class="even">
<td style="text-align: left;">Florida</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.251</td>
<td style="text-align: right;">0.126</td>
<td style="text-align: right;">17.793</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.631</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Georgia</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">55.093</td>
<td style="text-align: right;">42.792</td>
<td style="text-align: right;">1.287</td>
<td style="text-align: right;">0.200</td>
<td style="text-align: right;">0.629</td>
</tr>
<tr class="even">
<td style="text-align: left;">Georgia</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.559</td>
<td style="text-align: right;">0.145</td>
<td style="text-align: right;">17.678</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.629</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hawaii</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-3.694</td>
<td style="text-align: right;">6.379</td>
<td style="text-align: right;">-0.579</td>
<td style="text-align: right;">0.564</td>
<td style="text-align: right;">0.577</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hawaii</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.719</td>
<td style="text-align: right;">0.265</td>
<td style="text-align: right;">10.252</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.577</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Idaho</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">14.203</td>
<td style="text-align: right;">10.208</td>
<td style="text-align: right;">1.391</td>
<td style="text-align: right;">0.167</td>
<td style="text-align: right;">0.559</td>
</tr>
<tr class="even">
<td style="text-align: left;">Idaho</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.311</td>
<td style="text-align: right;">0.180</td>
<td style="text-align: right;">12.833</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.559</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Illinois</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-30.451</td>
<td style="text-align: right;">52.705</td>
<td style="text-align: right;">-0.578</td>
<td style="text-align: right;">0.564</td>
<td style="text-align: right;">0.552</td>
</tr>
<tr class="even">
<td style="text-align: left;">Illinois</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.538</td>
<td style="text-align: right;">0.169</td>
<td style="text-align: right;">15.045</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.552</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Indiana</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-54.247</td>
<td style="text-align: right;">33.394</td>
<td style="text-align: right;">-1.624</td>
<td style="text-align: right;">0.106</td>
<td style="text-align: right;">0.568</td>
</tr>
<tr class="even">
<td style="text-align: left;">Indiana</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.509</td>
<td style="text-align: right;">0.160</td>
<td style="text-align: right;">15.650</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.568</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Iowa</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-20.996</td>
<td style="text-align: right;">17.459</td>
<td style="text-align: right;">-1.203</td>
<td style="text-align: right;">0.231</td>
<td style="text-align: right;">0.492</td>
</tr>
<tr class="even">
<td style="text-align: left;">Iowa</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.228</td>
<td style="text-align: right;">0.177</td>
<td style="text-align: right;">12.608</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.492</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kansas</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">6.016</td>
<td style="text-align: right;">16.337</td>
<td style="text-align: right;">0.368</td>
<td style="text-align: right;">0.713</td>
<td style="text-align: right;">0.544</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kansas</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.440</td>
<td style="text-align: right;">0.178</td>
<td style="text-align: right;">13.728</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.544</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kentucky</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-4.659</td>
<td style="text-align: right;">26.144</td>
<td style="text-align: right;">-0.178</td>
<td style="text-align: right;">0.859</td>
<td style="text-align: right;">0.521</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kentucky</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.417</td>
<td style="text-align: right;">0.171</td>
<td style="text-align: right;">14.096</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.521</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Louisiana</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">12.740</td>
<td style="text-align: right;">22.704</td>
<td style="text-align: right;">0.561</td>
<td style="text-align: right;">0.575</td>
<td style="text-align: right;">0.612</td>
</tr>
<tr class="even">
<td style="text-align: left;">Louisiana</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.539</td>
<td style="text-align: right;">0.154</td>
<td style="text-align: right;">16.459</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.612</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Maine</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">24.393</td>
<td style="text-align: right;">13.605</td>
<td style="text-align: right;">1.793</td>
<td style="text-align: right;">0.076</td>
<td style="text-align: right;">0.238</td>
</tr>
<tr class="even">
<td style="text-align: left;">Maine</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.596</td>
<td style="text-align: right;">0.437</td>
<td style="text-align: right;">5.943</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.238</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Maryland</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-92.502</td>
<td style="text-align: right;">24.689</td>
<td style="text-align: right;">-3.747</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.558</td>
</tr>
<tr class="even">
<td style="text-align: left;">Maryland</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.600</td>
<td style="text-align: right;">0.173</td>
<td style="text-align: right;">15.036</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.558</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Massachusetts</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-80.090</td>
<td style="text-align: right;">27.111</td>
<td style="text-align: right;">-2.954</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">0.660</td>
</tr>
<tr class="even">
<td style="text-align: left;">Massachusetts</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.225</td>
<td style="text-align: right;">0.121</td>
<td style="text-align: right;">18.426</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.660</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Michigan</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-75.675</td>
<td style="text-align: right;">47.842</td>
<td style="text-align: right;">-1.582</td>
<td style="text-align: right;">0.115</td>
<td style="text-align: right;">0.601</td>
</tr>
<tr class="even">
<td style="text-align: left;">Michigan</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.659</td>
<td style="text-align: right;">0.161</td>
<td style="text-align: right;">16.546</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.601</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Minnesota</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-31.590</td>
<td style="text-align: right;">23.156</td>
<td style="text-align: right;">-1.364</td>
<td style="text-align: right;">0.174</td>
<td style="text-align: right;">0.471</td>
</tr>
<tr class="even">
<td style="text-align: left;">Minnesota</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.393</td>
<td style="text-align: right;">0.190</td>
<td style="text-align: right;">12.584</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.471</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mississippi</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">8.756</td>
<td style="text-align: right;">16.797</td>
<td style="text-align: right;">0.521</td>
<td style="text-align: right;">0.603</td>
<td style="text-align: right;">0.635</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mississippi</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.481</td>
<td style="text-align: right;">0.142</td>
<td style="text-align: right;">17.435</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.635</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Missouri</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-44.197</td>
<td style="text-align: right;">33.234</td>
<td style="text-align: right;">-1.330</td>
<td style="text-align: right;">0.185</td>
<td style="text-align: right;">0.534</td>
</tr>
<tr class="even">
<td style="text-align: left;">Missouri</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.536</td>
<td style="text-align: right;">0.178</td>
<td style="text-align: right;">14.231</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.534</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Montana</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">11.332</td>
<td style="text-align: right;">4.937</td>
<td style="text-align: right;">2.295</td>
<td style="text-align: right;">0.024</td>
<td style="text-align: right;">0.835</td>
</tr>
<tr class="even">
<td style="text-align: left;">Montana</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.410</td>
<td style="text-align: right;">0.106</td>
<td style="text-align: right;">22.641</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.835</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nebraska</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">10.989</td>
<td style="text-align: right;">-0.086</td>
<td style="text-align: right;">0.932</td>
<td style="text-align: right;">0.503</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nebraska</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.364</td>
<td style="text-align: right;">0.198</td>
<td style="text-align: right;">11.954</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.503</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nevada</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">4.124</td>
<td style="text-align: right;">15.928</td>
<td style="text-align: right;">0.259</td>
<td style="text-align: right;">0.796</td>
<td style="text-align: right;">0.560</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nevada</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.351</td>
<td style="text-align: right;">0.160</td>
<td style="text-align: right;">14.724</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.560</td>
</tr>
<tr class="odd">
<td style="text-align: left;">New Hampshire</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">12.934</td>
<td style="text-align: right;">12.054</td>
<td style="text-align: right;">1.073</td>
<td style="text-align: right;">0.286</td>
<td style="text-align: right;">0.236</td>
</tr>
<tr class="even">
<td style="text-align: left;">New Hampshire</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.150</td>
<td style="text-align: right;">0.382</td>
<td style="text-align: right;">5.621</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.236</td>
</tr>
<tr class="odd">
<td style="text-align: left;">New Jersey</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-192.886</td>
<td style="text-align: right;">32.751</td>
<td style="text-align: right;">-5.889</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.851</td>
</tr>
<tr class="even">
<td style="text-align: left;">New Jersey</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.630</td>
<td style="text-align: right;">0.082</td>
<td style="text-align: right;">32.217</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.851</td>
</tr>
<tr class="odd">
<td style="text-align: left;">New Mexico</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">24.966</td>
<td style="text-align: right;">12.325</td>
<td style="text-align: right;">2.026</td>
<td style="text-align: right;">0.044</td>
<td style="text-align: right;">0.576</td>
</tr>
<tr class="even">
<td style="text-align: left;">New Mexico</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.330</td>
<td style="text-align: right;">0.158</td>
<td style="text-align: right;">14.784</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.576</td>
</tr>
<tr class="odd">
<td style="text-align: left;">New York</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-75.879</td>
<td style="text-align: right;">46.889</td>
<td style="text-align: right;">-1.618</td>
<td style="text-align: right;">0.107</td>
<td style="text-align: right;">0.692</td>
</tr>
<tr class="even">
<td style="text-align: left;">New York</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.433</td>
<td style="text-align: right;">0.120</td>
<td style="text-align: right;">20.199</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.692</td>
</tr>
<tr class="odd">
<td style="text-align: left;">North Carolina</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">24.244</td>
<td style="text-align: right;">46.224</td>
<td style="text-align: right;">0.524</td>
<td style="text-align: right;">0.601</td>
<td style="text-align: right;">0.526</td>
</tr>
<tr class="even">
<td style="text-align: left;">North Carolina</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.503</td>
<td style="text-align: right;">0.176</td>
<td style="text-align: right;">14.239</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.526</td>
</tr>
<tr class="odd">
<td style="text-align: left;">North Dakota</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-6.396</td>
<td style="text-align: right;">4.148</td>
<td style="text-align: right;">-1.542</td>
<td style="text-align: right;">0.127</td>
<td style="text-align: right;">0.849</td>
</tr>
<tr class="even">
<td style="text-align: left;">North Dakota</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.026</td>
<td style="text-align: right;">0.093</td>
<td style="text-align: right;">21.759</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.849</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ohio</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-232.900</td>
<td style="text-align: right;">63.633</td>
<td style="text-align: right;">-3.660</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.598</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ohio</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.615</td>
<td style="text-align: right;">0.158</td>
<td style="text-align: right;">16.575</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.598</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oklahoma</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-13.884</td>
<td style="text-align: right;">20.507</td>
<td style="text-align: right;">-0.677</td>
<td style="text-align: right;">0.499</td>
<td style="text-align: right;">0.642</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oklahoma</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.356</td>
<td style="text-align: right;">0.132</td>
<td style="text-align: right;">17.811</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.642</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oregon</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">77.838</td>
<td style="text-align: right;">22.253</td>
<td style="text-align: right;">3.498</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.301</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oregon</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.692</td>
<td style="text-align: right;">0.311</td>
<td style="text-align: right;">8.655</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.301</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pennsylvania</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-180.602</td>
<td style="text-align: right;">66.304</td>
<td style="text-align: right;">-2.724</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: right;">0.589</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pennsylvania</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.560</td>
<td style="text-align: right;">0.157</td>
<td style="text-align: right;">16.319</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.589</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Puerto Rico</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">61.637</td>
<td style="text-align: right;">18.592</td>
<td style="text-align: right;">3.315</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.194</td>
</tr>
<tr class="even">
<td style="text-align: left;">Puerto Rico</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.378</td>
<td style="text-align: right;">0.384</td>
<td style="text-align: right;">6.195</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.194</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rhode Island</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">6.376</td>
<td style="text-align: right;">9.703</td>
<td style="text-align: right;">0.657</td>
<td style="text-align: right;">0.513</td>
<td style="text-align: right;">0.447</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rhode Island</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">1.784</td>
<td style="text-align: right;">0.198</td>
<td style="text-align: right;">9.027</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.447</td>
</tr>
<tr class="odd">
<td style="text-align: left;">South Carolina</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">62.602</td>
<td style="text-align: right;">24.499</td>
<td style="text-align: right;">2.555</td>
<td style="text-align: right;">0.011</td>
<td style="text-align: right;">0.581</td>
</tr>
<tr class="even">
<td style="text-align: left;">South Carolina</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.352</td>
<td style="text-align: right;">0.148</td>
<td style="text-align: right;">15.931</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.581</td>
</tr>
<tr class="odd">
<td style="text-align: left;">South Dakota</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-3.886</td>
<td style="text-align: right;">4.347</td>
<td style="text-align: right;">-0.894</td>
<td style="text-align: right;">0.374</td>
<td style="text-align: right;">0.857</td>
</tr>
<tr class="even">
<td style="text-align: left;">South Dakota</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.176</td>
<td style="text-align: right;">0.091</td>
<td style="text-align: right;">23.974</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.857</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tennessee</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-12.193</td>
<td style="text-align: right;">34.120</td>
<td style="text-align: right;">-0.357</td>
<td style="text-align: right;">0.721</td>
<td style="text-align: right;">0.626</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tennessee</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.478</td>
<td style="text-align: right;">0.141</td>
<td style="text-align: right;">17.553</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.626</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Texas</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">141.292</td>
<td style="text-align: right;">90.272</td>
<td style="text-align: right;">1.565</td>
<td style="text-align: right;">0.119</td>
<td style="text-align: right;">0.713</td>
</tr>
<tr class="even">
<td style="text-align: left;">Texas</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.298</td>
<td style="text-align: right;">0.107</td>
<td style="text-align: right;">21.424</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.713</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Utah</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">27.348</td>
<td style="text-align: right;">13.171</td>
<td style="text-align: right;">2.076</td>
<td style="text-align: right;">0.040</td>
<td style="text-align: right;">0.388</td>
</tr>
<tr class="even">
<td style="text-align: left;">Utah</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.334</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">9.320</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.388</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Vermont</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">14.422</td>
<td style="text-align: right;">3.972</td>
<td style="text-align: right;">3.631</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.507</td>
</tr>
<tr class="even">
<td style="text-align: left;">Vermont</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">3.512</td>
<td style="text-align: right;">0.427</td>
<td style="text-align: right;">8.232</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.507</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Virginia</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">32.897</td>
<td style="text-align: right;">35.446</td>
<td style="text-align: right;">0.928</td>
<td style="text-align: right;">0.355</td>
<td style="text-align: right;">0.462</td>
</tr>
<tr class="even">
<td style="text-align: left;">Virginia</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.584</td>
<td style="text-align: right;">0.206</td>
<td style="text-align: right;">12.545</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.462</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Washington</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">50.657</td>
<td style="text-align: right;">33.487</td>
<td style="text-align: right;">1.513</td>
<td style="text-align: right;">0.132</td>
<td style="text-align: right;">0.257</td>
</tr>
<tr class="even">
<td style="text-align: left;">Washington</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.550</td>
<td style="text-align: right;">0.319</td>
<td style="text-align: right;">8.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.257</td>
</tr>
<tr class="odd">
<td style="text-align: left;">West Virginia</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">21.232</td>
<td style="text-align: right;">15.280</td>
<td style="text-align: right;">1.390</td>
<td style="text-align: right;">0.167</td>
<td style="text-align: right;">0.493</td>
</tr>
<tr class="even">
<td style="text-align: left;">West Virginia</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.564</td>
<td style="text-align: right;">0.211</td>
<td style="text-align: right;">12.145</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.493</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wisconsin</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-42.048</td>
<td style="text-align: right;">27.464</td>
<td style="text-align: right;">-1.531</td>
<td style="text-align: right;">0.128</td>
<td style="text-align: right;">0.527</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wisconsin</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.594</td>
<td style="text-align: right;">0.186</td>
<td style="text-align: right;">13.935</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.527</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wyoming</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-1.791</td>
<td style="text-align: right;">4.104</td>
<td style="text-align: right;">-0.436</td>
<td style="text-align: right;">0.664</td>
<td style="text-align: right;">0.757</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wyoming</td>
<td style="text-align: left;">covid_deaths</td>
<td style="text-align: right;">2.458</td>
<td style="text-align: right;">0.163</td>
<td style="text-align: right;">15.086</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.757</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We are first using 2015-2019 US mortality data grouped by states to estimate the 2020-2023 mortality by all causes (not limited to deaths caused by Covid-19). Then we calculate excess mortality by subtracting the estimated deaths from observed deaths of 2020-2023. This is depicted as blue line in the plot. Now, we plot the deaths which the culprit is Covid-19 via red line to see whether the excess mortality is well explained by Covid-19. We can see that in most of the states, COVId-19 is indeed the main culprit of excess mortality from 2020-2023. However, some states such as New Hampshire, Oregon, Puerto Rico, and Washington do not have a similar trend of lines between COVID-19 deaths and Excess deaths, meaning COVID-19 does not explain the excess mortality that well.</p>
<p>Second, we conducted additional analysis of fitting the linear model with COVID-19 deaths being the covariate and excess deaths being the outcome variable. The results of the model advocated the findings that we have roughly found from the plot. The R-squared values of each state’s model showed that New Hampshire(0.236), Oregon(0.301), Puerto Rico(0.194), and Washington(0.257)’s respective R-squared values were all low compared to other states. Some states such as New Jersey, North Dakota, and South Dakota showed very high R-squared values of 0.851, 0.849, and 0.857 respectively which corresponded to the alignment of Covid caused deaths and excess deaths in the plot.</p>
<p>Overall, we can conclude that COVID-19 fairly explains the excess mortality in the United States during 2020-2023 well!</p>
</section>
<section id="q5.-for-each-period-compute-the-excess-mortality-rates-by-state.-describe-which-states-did-better-or-worse-during-the-different-periods." class="level2">
<h2 class="anchored" data-anchor-id="q5.-for-each-period-compute-the-excess-mortality-rates-by-state.-describe-which-states-did-better-or-worse-during-the-different-periods.">Q5. For each period compute the excess mortality rates by state. Describe which states did better or worse during the different periods.</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final-project_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 24%">
<col style="width: 13%">
<col style="width: 21%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">state_name</th>
<th style="text-align: right;">total_excess_deaths</th>
<th style="text-align: right;">population</th>
<th style="text-align: right;">excess_death_rate</th>
<th style="text-align: left;">Wave</th>
<th style="text-align: left;">wave</th>
<th style="text-align: right;">rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">South Dakota</td>
<td style="text-align: right;">16419.314</td>
<td style="text-align: right;">908473.0</td>
<td style="text-align: right;">1807.353</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mississippi</td>
<td style="text-align: right;">51633.512</td>
<td style="text-align: right;">2943234.4</td>
<td style="text-align: right;">1754.312</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oklahoma</td>
<td style="text-align: right;">70164.746</td>
<td style="text-align: right;">4020841.8</td>
<td style="text-align: right;">1745.026</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Arkansas</td>
<td style="text-align: right;">52176.618</td>
<td style="text-align: right;">3047415.4</td>
<td style="text-align: right;">1712.160</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">New Mexico</td>
<td style="text-align: right;">35110.491</td>
<td style="text-align: right;">2114723.2</td>
<td style="text-align: right;">1660.288</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hawaii</td>
<td style="text-align: right;">1447.598</td>
<td style="text-align: right;">1439376.6</td>
<td style="text-align: right;">100.571</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: right;">52</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Washington</td>
<td style="text-align: right;">34028.332</td>
<td style="text-align: right;">7780112.0</td>
<td style="text-align: right;">437.376</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: right;">51</td>
</tr>
<tr class="even">
<td style="text-align: left;">New Hampshire</td>
<td style="text-align: right;">6775.909</td>
<td style="text-align: right;">1396105.8</td>
<td style="text-align: right;">485.344</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: right;">50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Maine</td>
<td style="text-align: right;">6793.006</td>
<td style="text-align: right;">1385767.6</td>
<td style="text-align: right;">490.198</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: right;">49</td>
</tr>
<tr class="even">
<td style="text-align: left;">Massachusetts</td>
<td style="text-align: right;">37083.374</td>
<td style="text-align: right;">6994548.2</td>
<td style="text-align: right;">530.175</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: left;">Wave 1</td>
<td style="text-align: right;">48</td>
</tr>
<tr class="odd">
<td style="text-align: left;">West Virginia</td>
<td style="text-align: right;">29595.602</td>
<td style="text-align: right;">1775810.4</td>
<td style="text-align: right;">1666.597</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alaska</td>
<td style="text-align: right;">11892.841</td>
<td style="text-align: right;">733124.0</td>
<td style="text-align: right;">1622.214</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Montana</td>
<td style="text-align: right;">17743.049</td>
<td style="text-align: right;">1119461.6</td>
<td style="text-align: right;">1584.963</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wyoming</td>
<td style="text-align: right;">8220.787</td>
<td style="text-align: right;">581598.8</td>
<td style="text-align: right;">1413.481</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mississippi</td>
<td style="text-align: right;">41573.242</td>
<td style="text-align: right;">2943234.4</td>
<td style="text-align: right;">1412.502</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">New Jersey</td>
<td style="text-align: right;">13175.832</td>
<td style="text-align: right;">9275981.8</td>
<td style="text-align: right;">142.042</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: right;">52</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Massachusetts</td>
<td style="text-align: right;">11776.964</td>
<td style="text-align: right;">6994548.2</td>
<td style="text-align: right;">168.373</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: right;">51</td>
</tr>
<tr class="even">
<td style="text-align: left;">Maryland</td>
<td style="text-align: right;">11487.566</td>
<td style="text-align: right;">6171589.2</td>
<td style="text-align: right;">186.136</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: right;">50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Connecticut</td>
<td style="text-align: right;">8306.713</td>
<td style="text-align: right;">3610627.6</td>
<td style="text-align: right;">230.063</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: right;">49</td>
</tr>
<tr class="even">
<td style="text-align: left;">New York</td>
<td style="text-align: right;">50117.643</td>
<td style="text-align: right;">19713122.4</td>
<td style="text-align: right;">254.235</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: left;">Wave 2</td>
<td style="text-align: right;">48</td>
</tr>
<tr class="odd">
<td style="text-align: left;">West Virginia</td>
<td style="text-align: right;">22867.470</td>
<td style="text-align: right;">1775810.4</td>
<td style="text-align: right;">1287.720</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">New Mexico</td>
<td style="text-align: right;">23042.651</td>
<td style="text-align: right;">2114723.2</td>
<td style="text-align: right;">1089.630</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oklahoma</td>
<td style="text-align: right;">41694.305</td>
<td style="text-align: right;">4020841.8</td>
<td style="text-align: right;">1036.955</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kentucky</td>
<td style="text-align: right;">45350.159</td>
<td style="text-align: right;">4516205.0</td>
<td style="text-align: right;">1004.165</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Arizona</td>
<td style="text-align: right;">70906.708</td>
<td style="text-align: right;">7355304.6</td>
<td style="text-align: right;">964.021</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hawaii</td>
<td style="text-align: right;">4758.577</td>
<td style="text-align: right;">1439376.6</td>
<td style="text-align: right;">330.600</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: right;">52</td>
</tr>
<tr class="odd">
<td style="text-align: left;">New York</td>
<td style="text-align: right;">66754.672</td>
<td style="text-align: right;">19713122.4</td>
<td style="text-align: right;">338.631</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: right;">51</td>
</tr>
<tr class="even">
<td style="text-align: left;">Utah</td>
<td style="text-align: right;">13825.447</td>
<td style="text-align: right;">3377227.8</td>
<td style="text-align: right;">409.373</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: right;">50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Massachusetts</td>
<td style="text-align: right;">29029.613</td>
<td style="text-align: right;">6994548.2</td>
<td style="text-align: right;">415.032</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: right;">49</td>
</tr>
<tr class="even">
<td style="text-align: left;">Washington</td>
<td style="text-align: right;">36644.443</td>
<td style="text-align: right;">7780112.0</td>
<td style="text-align: right;">471.001</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: left;">Wave 3</td>
<td style="text-align: right;">48</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Wave 1 (Oct 1, 2020 – Apr 1, 2021):</p>
<p>Highest Excess Mortality Rates: South Dakota, Mississippi, Oklahoma, Arkansas, New Mexico</p>
<p>Lowest Excess Mortality Rates: Hawaii, Washington, New Hampshire, Maine, Massachusetts</p>
<p>Wave 2 (Jul 1, 2021 – Dec 1, 2021):</p>
<p>Highest Excess Mortality Rates: West Virginia, Alaska, Montana, Wyoming, Mississippi</p>
<p>Lowest Excess Mortality Rates: New Jersey, Massachusetts, Maryland, Connecticut, New York</p>
<p>Wave 3 (Dec 2, 2021 – Apr 1, 2022):</p>
<p>Highest Excess Mortality Rates: West Virginia, New Mexico, Oklahoma, Kentucky, Arizona</p>
<p>Lowest Excess Mortality Rates: Hawaii, New York, Utah, Massachusetts, Washington</p>
<p>Throughout the pandemic, certain states consistently experienced higher excess mortality rates, notably Oklahoma, Mississippi, and West Virginia. These states faced unique challenges, including lower vaccination uptake, limited access to healthcare in rural areas, and delayed or less stringent public health measures. Additionally, a higher prevalence of pre-existing health conditions such as obesity, diabetes, and cardiovascular diseases likely exacerbated the impact of COVID-19. These structural and behavioral factors contributed to their frequent appearance among the states with the highest excess mortality across all waves.</p>
<p>In contrast, states like Hawaii, Washington, and Massachusetts consistently ranked among those with the lowest excess mortality rates. These states benefitted from strong healthcare systems, better access to medical resources, and early implementation of comprehensive public health strategies. High vaccination rates, coupled with effective public policies and greater compliance with mitigation measures, played a critical role in reducing mortality. These factors highlight how proactive and sustained public health interventions can mitigate the toll of the pandemic, even in the face of widespread challenges.</p>
<p>The availability and uptake of vaccines emerged as a decisive factor influencing trends in excess mortality over time. States that prioritized vaccine distribution and achieved higher coverage witnessed declining excess mortality rates in later waves. Conversely, states slower to adopt widespread vaccination or preventive measures often struggled to control mortality rates. These findings underscore the vital role of public health policies and vaccination in shaping outcomes during a public health crisis, emphasizing the importance of equitable and efficient health resource allocation to protect vulnerable populations.</p>
</section>
</section>
<section id="supplementary-methods" class="level1">
<h1>Supplementary Methods</h1>
<section id="death-rate-of-each-state-3-waves" class="level2">
<h2 class="anchored" data-anchor-id="death-rate-of-each-state-3-waves">Death rate of each state (3 waves)</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final-project_files/figure-html/death%20rate%20by%20state-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final-project_files/figure-html/death%20rate%20by%20state-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final-project_files/figure-html/death%20rate%20by%20state-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="pair-wise-comparison-of-the-cfr-hr-and-dp-using-statistical-tests" class="level2">
<h2 class="anchored" data-anchor-id="pair-wise-comparison-of-the-cfr-hr-and-dp-using-statistical-tests">Pair-wise comparison of the CFR, HR, and DP using statistical tests</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final-project_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final-project_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final-project_files/figure-html/unnamed-chunk-7-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>

</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-alcendor2020racial" class="csl-entry" role="listitem">
Alcendor, Donald J. 2020. <span>“Racial Disparities-Associated COVID-19 Mortality Among Minority Populations in the US.”</span> <em>Journal of Clinical Medicine</em> 9 (8): 2442.
</div>
<div id="ref-covid2021modeling" class="csl-entry" role="listitem">
Covid, IHME, and Forecasting Team. 2021. <span>“Modeling COVID-19 Scenarios for the United States.”</span> <em>Nature Medicine</em> 27 (1): 94.
</div>
<div id="ref-gao2021systematic" class="csl-entry" role="listitem">
Gao, Zhiru, Yinghui Xu, Chao Sun, Xu Wang, Ye Guo, Shi Qiu, and Kewei Ma. 2021. <span>“A Systematic Review of Asymptomatic Infections with COVID-19.”</span> <em>Journal of Microbiology, Immunology and Infection</em> 54 (1): 12–16.
</div>
<div id="ref-koh2020covid" class="csl-entry" role="listitem">
Koh, David. 2020. <span>“COVID-19 Lockdowns Throughout the World.”</span> <em>Occupational Medicine</em> 70 (5): 322–22.
</div>
<div id="ref-madabhavi2020covid" class="csl-entry" role="listitem">
Madabhavi, Irappa, Malay Sarkar, and Nagaveni Kadakol. 2020. <span>“COVID-19: A Review.”</span> <em>Monaldi Archives for Chest Disease</em> 90 (2).
</div>
<div id="ref-omer2020covid" class="csl-entry" role="listitem">
Omer, Saad B, Preeti Malani, and Carlos Del Rio. 2020. <span>“The COVID-19 Pandemic in the US: A Clinical Update.”</span> <em>Jama</em> 323 (18): 1767–68.
</div>
<div id="ref-shi_2020_an" class="csl-entry" role="listitem">
Shi, Yu, Gang Wang, Xiao-peng Cai, Jing-wen Deng, Lin Zheng, Hai-hong Zhu, Min Zheng, Bo Yang, and Zhi Chen. 2020. <span>“An Overview of COVID-19.”</span> <em>Journal of Zhejiang University-SCIENCE B</em> 21 (May): 343–60. <a href="https://doi.org/10.1631/jzus.b2000083">https://doi.org/10.1631/jzus.b2000083</a>.
</div>
<div id="ref-stasi2020treatment" class="csl-entry" role="listitem">
Stasi, Cristina, Silvia Fallani, Fabio Voller, and Caterina Silvestri. 2020. <span>“Treatment for COVID-19: An Overview.”</span> <em>European Journal of Pharmacology</em> 889: 173644.
</div>
<div id="ref-vasireddy2021review" class="csl-entry" role="listitem">
Vasireddy, Deepa, Rachana Vanaparthy, Gisha Mohan, Srikrishna Varun Malayala, and Paavani Atluri. 2021. <span>“Review of COVID-19 Variants and COVID-19 Vaccine Efficacy: What the Clinician Should Know?”</span> <em>Journal of Clinical Medicine Research</em> 13 (6): 317.
</div>
<div id="ref-wilder2021disproportionate" class="csl-entry" role="listitem">
Wilder, Julius M. 2021. <span>“The Disproportionate Impact of COVID-19 on Racial and Ethnic Minorities in the United States.”</span> <em>Clinical Infectious Diseases</em>. Oxford University Press US.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<script src="final-project_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>